version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "environments/staging/profile_assets_manager"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "environments/production/profile_assets_manager"
    schedule:
      interval: "monthly"

