name: terraform_format

on:
  pull_request:
    paths:
      - ".github/workflows/terraform_format.yml"
      - "**/*.tf"

jobs:
  fmt:
    name: terraform_format
    runs-on: ubuntu-24.04
    steps:
      - name: リポジトリを取得
        uses: actions/checkout@v5

      - name: Terraformをセットアップ
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"

      - name: Terraformのコードがフォーマット済みか確認
        run: terraform fmt -check

